use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
target 'FF' do
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'FacebookShare'
    pod 'MessageKit'
end
