# Generated by Django 2.2.4 on 2019-10-06 21:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lon',
            new_name='longitude',
        ),
        migrations.AlterField(
            model_name='user',
            name='lobby_expiration',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 6, 21, 40, 37, 663368, tzinfo=utc)),
        ),
    ]
