# Generated by Django 2.2.4 on 2019-10-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ffrequest',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
