# Generated by Django 2.2.4 on 2019-10-28 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191028_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='facebook_ID',
            new_name='fb_id',
        ),
    ]
