# Generated by Django 2.2.4 on 2019-08-29 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='online_until',
        ),
    ]
