# Generated by Django 2.2.4 on 2019-08-31 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190831_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lobby_expiration',
        ),
    ]
