# Generated by Django 2.2.4 on 2019-08-31 18:28

import datetime
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_lobby_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lobby_expiration',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 31, 18, 28, 40, 442126)),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[(users.models.StatusEnum('pending'), 'pending'), (users.models.StatusEnum('accepted'), 'accepted'), (users.models.StatusEnum('rejected'), 'rejected'), (users.models.StatusEnum('expired'), 'expired'), (users.models.StatusEnum('cancelled'), 'cancelled')], max_length=255),
        ),
    ]
